name: GH Workflow 2
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo "GH Action"
          pwd
          uname -a
          env
